# Generated by Django 5.0.6 on 2025-03-02 13:06

import Chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderTable',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, validators=[Chat.models.alphanumeric_validator])),
                ('dateCreated', models.CharField(blank=True, max_length=60, null=True)),
                ('account_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='FileTable',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, validators=[Chat.models.alphanumeric_validator])),
                ('dateCreated', models.CharField(blank=True, max_length=60, null=True)),
                ('size', models.CharField(blank=True, max_length=60, null=True)),
                ('fileUrl', models.TextField(blank=True, null=True, validators=[Chat.models.alphanumeric_validator])),
                ('type', models.TextField(blank=True, null=True, validators=[Chat.models.alphanumeric_validator])),
                ('account_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Chat.foldertable')),
            ],
        ),
    ]
