# Generated by Django 5.0.6 on 2025-03-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_foldertable_filetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ProfileAbout',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
