# Generated by Django 5.0.6 on 2025-03-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_account_profileabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='YoutubeChannels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
