# Generated by Django 5.0.6 on 2025-03-18 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_account_youtubechannels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreationStateManager',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PostContentContainer', models.JSONField(blank=True, null=True)),
                ('dateModified', models.CharField(blank=True, max_length=60, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('account_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_manager', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
