# Generated by Django 5.0.6 on 2025-03-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_creationstatemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='creationstatemanager',
            name='AiPage',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
