# Generated by Django 5.0.6 on 2025-03-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_creationstatemanager_requestkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notification_sound',
            field=models.CharField(choices=[('bell-notification-933.wav', 'Bell Notification'), ('bubble-pop-up-alert-notification-2357.wav', 'Bubble Pop-Up Alert'), ('correct-answer-tone-2870.wav', 'Correct Answer Tone'), ('gaming-lock-2848.wav', 'Gaming Lock'), ('happy-bells-notification-937.wav', 'Happy Bells Notification'), ('long-pop-2358.wav', 'Long Pop'), ('notification.wav', 'Notification'), ('positive-notification-951.wav', 'Positive Notification'), ('sci-fi-click-900.wav', 'Sci-Fi Click'), ('software-interface-back-2575.wav', 'Software Interface Back'), ('software-interface-start-2574.wav', 'Software Interface Start'), ('sci-fi-confirmation.wav', 'sci-fi-confirmation.wav')], default='chime', help_text='Select preferred notification sound effect.', max_length=50, verbose_name='Notification effect'),
        ),
    ]
